apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: Comfyui-Cluster
  region: us-west-2
nodeGroups:
  - name: SD-MNG-NG
    instanceType: g5.xlarge
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
