apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: Comfyui-Cluster
  region: us-west-2
  # SD-MNG-NG use spot instances
managedNodeGroups:
  - name: SD-MNG-NG
    launchTemplate:
      version: 1
      id: lt-07de1904fdb331822
