apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: Comfyui-Cluster
  region: us-west-2
managedNodeGroups:
  - name: LW-NodeGroup
    launchTemplate:
      id: Comfyui-EKS-LW-Node
      version: "1"
