apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: Comfyui-Cluster
  region: us-west-2
managedNodeGroups:
  - name: LW-NodeGroup
    launchTemplate:
      id: lt-0a194be3a6c28c4a2
      version: "1"
