apiVersion: v1
kind: PersistentVolume
metadata:
  name: comfyui-inputs-pv
spec:
  capacity:
    storage: 1200Gi # ignored, required
  accessModes:
    - ReadWriteMany # supported options: ReadWriteMany / ReadOnlyMany
  mountOptions:
    - allow-delete
    - region us-west-2
  csi:
    driver: s3.csi.aws.com # required
    volumeHandle: s3-csi-driver-volume-inputs # need to be unique
    volumeAttributes:
      bucketName: comfyui-inputs-123456789012-us-west-2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-inputs-pvc
spec:
  accessModes:
    - ReadWriteMany # supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # required for static provisioning
  resources:
    requests:
      storage: 1200Gi # ignored, required
  volumeName: comfyui-inputs-pv
