apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-models-pvc
spec:
  accessModes:
    - ReadOnlyMany # supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: comfyui-models-sc # required for static provisioning
  resources:
    requests:
      storage: 1200Gi # ignored, required
  volumeName: comfyui-models-pv
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: comfyui-models-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-us-west-2
  fileSystemId: fs-026bb4e33bea77857 # EFS file system ID
  directoryPerms: "700"
