apiVersion: v1
kind: PersistentVolume
metadata:
  name: comfyui-outputs-pv
spec:
  capacity:
    storage: 1000Gi # ignored, required
  accessModes:
    - ReadWriteMany # supported options: ReadWriteMany / ReadOnlyMany
  mountOptions:
    - allow-delete
    - region us-west-2
  csi:
    driver: efs.csi.aws.com # required
    volumeHandle: efs-csi-driver-volume-outputs # need to be unique
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-outputs-pvc
spec:
  accessModes:
    - ReadWriteMany # supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: comfyui-outputs-sc # required for static provisioning
  resources:
    requests:
      storage: 1200Gi # ignored, required
  volumeName: comfyui-outputs-pv
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: comfyui-outputs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-us-west-2
  fileSystemId: fs-026bb4e33bea77857 # EFS file system ID
  directoryPerms: "700"
