# define storage class, efs file system ID, and directory permissions
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: stable-diffusion-runtime-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: efs.csi.aws.com
parameters:
  fileSystemId: fs-0d91f2f3f42f755f4:/ComfyUI
  directoryPerms: "755"
---
# define persistent volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stable-diffusion-runtime-pv
  labels:
    type: local
    app: comfyui
spec:
  storageClassName: stable-diffusion-runtime-sc
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0d91f2f3f42f755f4
    volumeAttributes:
      availabilityZon: us-west-2a
---
# define persistent volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stable-diffusion-runtime-pvc
spec:
  storageClassName: stable-diffusion-runtime-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
      storageClassName: stable-diffusion-runtime-sc
  volumeName: stable-diffusion-runtime-pv
