apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stable-diffusion-runtime-pvc
spec:
  accessModes:
    - ReadOnlyMany # supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: stable-diffusion-runtime-sc # required for static provisioning
  resources:
    requests:
      storage: 1200Gi # ignored, required
  volumeName: stable-diffusion-runtime-pv
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: stable-diffusion-runtime
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-us-west-2
  fileSystemId: fs-0d91f2f3f42f755f4:/ComfyUI # EFS file system ID
  directoryPerms: "700"
