# define storage class, efs file system ID, and directory permissions
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sd-std-runtime-sc
provisioner: efs.csi.aws.com
---
# define persistent volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sd-std-runtime-pvc
spec:
  storageClassName: sd-std-runtime-sc
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  dataSource:
    name: sd-std-runtime-pv
    kind: AWSElasticsFilesystem
  resources:
    requests:
      storage: 120Gi
