apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-users-pvc
spec:
  accessModes:
    - ReadWriteMany # supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: comfyui-users-sc # required for static provisioning
  resources:
    requests:
      storage: 1200Gi # ignored, required
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: comfyui-users-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-us-west-2
  fileSystemId: fs-026bb4e33bea77857 # user, input, output, temp EFS file system ID
  directoryPerms: "766"
